name: mindlink
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2

  # ✅ Updated Firebase dependencies (mutually compatible)
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.5
  firebase_messaging: ^15.1.5

  # ✅ Other libraries
  modal_progress_hud_nsn: ^0.5.1
  encrypt: ^5.0.1
  crypto: ^3.0.3
  http: ^1.2.2
  provider: ^6.1.2
  syncfusion_flutter_charts: ^25.2.4
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
